
# Production Config Settings
spring:
  application:
    name: eRegistrarWebAPI
  main:
    banner-mode: off
  # Datasource config settings
  datasource:
    url: jdbc:mysql://localhost:3306/swe-lab11-student-registration-system
    username: root
    password: password
  # JPA/Hibernate config settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: off
